### ISSUE TITLE
請問會開發歐付寶ATM / ATM櫃員機模組嗎?

### ISSUE THREAD

**Issue by ironman852** [iHostUP/WHMCS_AllPay_Mod#1]
請問會開發歐付寶其它金流模組嗎?
如網路ATM / ATM櫃員機模組(虛擬帳號)
謝謝

**Comment by ian74** [comment]
會的
目前我們還在進行其他模組的整合
以及現有金流閘道模組安全性升級
虛擬帳號會在安全性升級後的下一個版本發行！
