### ISSUE TITLE
導往刷卡頁後出現錯誤

### ISSUE THREAD

**Issue by ironman852** [iHostUP/WHMCS_AllPay_Mod#2]
有在 WHMCS 歐付寶金流模組信用卡模組填入歐付寶廠商ID
其他都不用填嗎?
但按刷卡後就被導往以下頁面
https://payment.allpay.com.tw/bank/PaymentCenter/cntnotlogin/credit/result

付款失敗！
訊息代碼：10100113
訊息說明：GwID Is Error.

歐付寶廠商後台內的系統介接資訊 只需要填商店代號就好了嗎?
其它如HashKey、HashIV都不用填在WHMCS ?

歐付寶那的接收商品異常網址、取消訂單回傳網址、一般商品履約完成回傳網址
這些也都不用填在歐付寶是嗎?

謝謝

**Comment by ian74** [comment]
您好:

1.您必須到廠商->系統開發管理->系統介接設定->後台允許的IP
 將WHMCS所在的伺服器IP填入
並將"是否接收付款成功通知"勾選是
並在後台選取回傳額外資訊
另外官方生成 CheckMacValue API已經包含HashKey及HashIV產生功能
您不需要再填入

2.商品異常網址、取消訂單回傳網址、一般商品履約完成等功能
尚未完全支援WHMCS API 若開放使用會導致商品處理問題
故信用卡部分是每次點選刷卡按鈕就產生一次新訂單
您不需要手動取消訂單 

若還遇到其他問題 歡迎您詢問 謝謝

**Comment by ironman852** [comment]
CheckMacValue 是我要填在哪裡嗎? 還是不需做任何動作?

**Comment by ian74** [comment]
您無須進行任何動作
系統會自動幫您生成

**Comment by ironman852** [comment]
還是一樣出錯ㄝ
已加主機IP

**Comment by ironman852** [comment]
可以了
是歐付寶那邊的問題
謝謝
