### ISSUE TITLE
可否加入手續費功能?

### ISSUE THREAD

**Issue by ironman852** [iHostUP/WHMCS_AllPay_Mod#3]
金流模組可否加入手續費功能?
謝謝

**Comment by ian74** [comment]
您好:

手續費功能
是WHMCS產生帳單時需要新增帳單內容的功能
與歐付寶模組無關
您可至WHMCS官網尋找相關模組使用
以下提供給您一款免費的手續費功能模組
https://www.whmcs.com/appstore/4046/Gateway-Fees.html

謝謝

**Comment by ironman852** [comment]
好像不能下載，要付費了

**Comment by ian74** [comment]
您好

這部分可能就要請您斟酌是否付費使用了
手續費模組部份不在本次開發計畫上 

謝謝

**Comment by ironman852** [comment]
OkOk，謝謝您
